/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:a3c020ad-32f7-403b-a75b-bff6b8ab063b",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_e3TqGI5PR",
    "aws_user_pools_web_client_id": "1l3tf271h2qv74atcaccdm7eut",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5m3fgl5v5rb6bjwse2tsubfgd4.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "agridataappimagecontentbucket164209-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "aws_mobile_analytics_app_id": "641129bfeba2495d9d937090ecc989f7",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
